apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ks4web
  name: ks4web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: ks4web
  type: LoadBalancer
status:
  loadBalancer: {}
