apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: ks4web
  name: ks4web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ks4web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ks4web
    spec:
      containers:
      - image: ks4webimage:latest
        name: ks4web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
          - mountPath: /app/src
            name: frontend
      - image: ks4webserverimage:latest
        name: ks4webserver
        imagePullPolicy: IfNotPresent
        command: ["python"]
        args: ["-m", "flask", "run"]
        env:
        - name: FLASK_DEBUG
          value: "1"
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
          - mountPath: /server
            name: python-server
      volumes:
      - name: python-server
        hostPath:
          path: /mounted-ks4-src/server
      - name: frontend
        hostPath:
          path: /mounted-ks4-src/app/src
status: {}
