apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: ks5web
  name: ks5web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ks5web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ks5web
    spec:
      containers:
      - image: ks5webserverimage:latest
        name: ks5webserver
        imagePullPolicy: IfNotPresent
        env:
        - name: FLASK_DEBUG
          value: "1"
        - name: FLASK_CONFIG
          value: "testing"
        ports:
        - containerPort: 5000
        resources: {}
status: {}
