apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ksweb
  name: ksweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: ksweb
  type: LoadBalancer
status:
  loadBalancer: {}
