apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: ks3web
  name: ks3web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ks3web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ks3web
    spec:
      containers:
      - image: ks3webimage:latest
        name: ks3web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
          - mountPath: /app/src
            name: frontend
      volumes:
      - name: frontend
        hostPath:
          path: /mounted-ks3-app-src/app/src
status: {}
